### ISSUE TITLE
HTML alt atttibuten ontbreken - Renzo

### ISSUE THREAD

**Issue by saschavanvliet** [RenzoWille/squad-page-rmr#1]
Html validator: Je had een paar foutjes die tevoorschijn kwamen in de html validator. Zorg ervoor dat je gebruik maakt van alt attributen. Op deze manier kunnen mensen die slechtziend zijn ook navigeren op jouw website. 
https://validator.w3.org/nu/?doc=https%3A%2F%2Frenzowille.github.io%2Fsquad-page-rmr%2Findexrenzo.html

**Comment by RenzoWille** [comment]
Thanks het is geregeld
